development:
  dialect: sqlite3
  datasource: test.db
  dir: migrations/test
  table: gorp_migrations

mysql:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${DATABASE_NAME}?parseTime=true
  dir: migrations/mysql
  table: gorp_migrations

mssql:
  dialect: mssql
  datasource: server=${MSSQL_HOST};user id=${MSSQL_USER};password=${MSSQL_PASSWORD};port=${MSSQL_PORT};database=${DATABASE_NAME};
  dir: migrations/mssql
  table: gorp_migrations

main:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} port=${POSTGRES_PORT} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${DATABASE_NAME} sslmode=disable
  dir: migrations/main
  table: gorp_migrations
# sh -c "export POSTGRES_HOST='127.0.0.1' && export POSTGRES_PORT='5432' && export POSTGRES_USER='postgres' && export POSTGRES_PASSWORD='password' && export DATABASE_NAME='db_name' && sql-migrate down -env=main"
