// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Permission struct {
	ID           int32
	PermissionID int32
	Name         string
	UserID       pgtype.Int4
	GroupID      pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type Token struct {
	ID             int32
	Token          string
	IsRefreshToken bool
	UserID         int32
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID                   int32
	PhoneNumber          string
	Email                pgtype.Text
	Password             string
	Profile              pgtype.Text
	FirstName            pgtype.Text
	LastName             pgtype.Text
	DisplayName          string
	Gender               int32
	IsActive             bool
	Registered           bool
	DeactivationReason   pgtype.Text
	IsAdmin              bool
	OtpRemainingAttempts int32
	OtpCode              pgtype.Int4
	OtpDueDate           pgtype.Timestamptz
	IsSuperuser          bool
	CreatedAt            pgtype.Timestamptz
}

type UsersGroup struct {
	ID        int32
	UserID    int32
	GroupID   int32
	CreatedAt pgtype.Timestamptz
}
