// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	_ "embed"
	g "service/global"

	"github.com/golodash/godash/strings"
	"github.com/swaggo/swag"
)

//go:embed swagger.json
var docTemplate string

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          g.Version,
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            strings.StartCase(g.Name),
	Description:      g.Description,
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
